### ISSUE TITLE
LICENSE file missing

### ISSUE THREAD

**Issue by chriscamicas** [consultingwerk/ADE-Sourcecode#1]
Hi Mike,

I'm working on an extension for VSCode to add ABL Language support.
It's still in its early stage, but I'd like to include part of the code of this project (starting with the ABLUnit part).

What is exactly the LICENSE associated with this repository/source code ?
I've read it's Progress "Community Code Share License Agreement" but I couldn't find the exact terms.

I'd be nice to add a LICENSE file to clarify the situation.

My extension (forked from an existing one, but it's just the beginning) :
https://github.com/chriscamicas/vscode-abl
https://marketplace.visualstudio.com/items?itemName=chriscamicas.openedge-abl

On the other side, do you allow contributions and pull request ?
I may contribute to some ABLUnit improvement.

Thanks

**Comment by mikefechner** [comment]
The purpose of this repo is to provide simple access to the ADE source code deployments from Progress Software. Progress does only provide the ADE source code as a ZIP or tar file downloads from Progress communities.

So this repo is not intended to be a base for collaborative development.

If you want to discuss enhancements to ABLUnit, please email me directly.

I will look for a license definition to maker things clearer. But the right party to address that question to would be Progress Software.

Von meinem iPad gesendet

Am 22.07.2017 um 05:57 schrieb chriscamicas <notifications@github.com<mailto:notifications@github.com>>:


Hi Mike,

I'm working on an extension for VSCode to add ABL Language support.
It's still in its early stage, but I'd like to include part of the code of this project (starting with the ABLUnit part).

What is exactly the LICENSE associated with this repository/source code ?
I've read it's Progress "Community Code Share License Agreement" but I couldn't find the exact terms.

I'd be nice to add a LICENSE file to clarify the situation.

My extension (forked from an existing one, but it's just the beginning) :
https://github.com/chriscamicas/vscode-abl
https://marketplace.visualstudio.com/items?itemName=chriscamicas.openedge-abl

On the other side, do you allow contributions and pull request ?
I may contribute to some ABLUnit improvement.

Thanks

**Comment by chriscamicas** [comment]
Okay, thanks Mike for the reply.
FYI, I found the Code-Share agreement : https://community.progress.com/community_groups/w/communitygeneral/109.code-share-disclaimer-agreement
